Repository icatproject/icat.oaipmh, pull requests merged in 2023-07, with the labels that each got.

#33 Do not overwrite setup.properties or logback.xml in the test install directory
  src/test/scripts/prepare_test.py
Labels: enhancement, test suite

#23 Keep exception info during initialization
  src/main/java/org/icatproject/icat_oaipmh/RequestInterface.java
  src/main/java/org/icatproject/icat_oaipmh/ResponseBuilder.java
  src/main/java/org/icatproject/icat_oaipmh/exceptions/InternalException.java
Labels: enhancement

#34 Consistently name XSLT files *.xslt
  src/main/config/oai_datacite_transformer.xslt.example
  src/main/config/oai_dc_transformer.xslt.example
  src/main/config/run.properties.example
  src/main/java/org/icatproject/icat_oaipmh/MetadataFormat.java
  src/site/xhtml/installation.xhtml.vm
  src/test/resources/oai_datacite.xslt
  src/test/resources/oai_dc.xslt
  src/test/scripts/prepare_test.py
Labels: documentation
